receivers:
  otlp:
    protocols:
      grpc:
exporters:
  otlp/elastic:
    endpoint: https://f896c493d1284f4cb117a705d664bf09.apm.us-central1.gcp.cloud.es.io:443
    headers:
      Authorization: "Bearer 86KQgPsVaaRkSklPCF"
  logging:
    verbosity: detailed
service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [logging, otlp/elastic]
    traces:
      receivers: [otlp]
      exporters: [logging, otlp/elastic]
    logs:
      receivers: [otlp]
      exporters: [logging, otlp/elastic]