receivers:
  otlp:
    protocols:
      grpc:
exporters:
  otlp/elastic:
    endpoint: https://7a0e7fa66e3c4435bc8b2527a9ee6bef.apm.us-central1.gcp.cloud.es.io:443
    headers:
      Authorization: "Bearer mR0A8CCNHthGzL4OxV"
  logging:
    verbosity: detailed
service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [logging, otlp/elastic]
    traces:
      receivers: [otlp]
      exporters: [logging, otlp/elastic]
    logs:
      receivers: [otlp]
      exporters: [logging, otlp/elastic]