receivers:
  otlp:
    protocols:
      grpc:
exporters:
  otlp/elastic:
    endpoint: https://083c75913e614011b0ef1afd98bdfd98.apm.us-central1.gcp.cloud.es.io:443
    headers:
      Authorization: "Bearer TwNVPjMQ7evWJZxMXS"
  logging:
    verbosity: detailed
service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [logging, otlp/elastic]
    traces:
      receivers: [otlp]
      exporters: [logging, otlp/elastic]
    logs:
      receivers: [otlp]
      exporters: [logging, otlp/elastic]